name: autowgk
version: ${project.build.version}
description: Wgk Fight Manager without Supporter 
website: myplayplanet.net
authors: [Luki110998, Postremus, fly4lol]
main: de.fly4lol.autowgk.Main
depend: [SQLApi, WarGear, WorldEdit]